import { MaterialItem, ConstructionSite } from './types';

export const mockSites: ConstructionSite[] = [
  {
    id: 'site-1',
    name: 'Proyek Sudirman Plaza',
    code: 'SP',
    location: 'Jakarta Selatan, DKI Jakarta',
    manager: 'Ir. Budi Santoso',
    latitude: -6.2146,
    longitude: 106.8272,
  },
  {
    id: 'site-2',
    name: 'Proyek Apartment Grand Merdeka',
    code: 'GM',
    location: 'Bandung Wetan, Jawa Barat',
    manager: 'Siti Rahmawati, M.T.',
    latitude: -6.9147,
    longitude: 107.6098,
  },
  {
    id: 'site-3',
    name: 'Proyek Harbour View Mall',
    code: 'HM',
    location: 'Tanjung Perak, Surabaya, Jawa Timur',
    manager: 'Hendra Wijaya, S.T.',
    latitude: -7.2053,
    longitude: 112.7278,
  },
  {
    id: 'site-4',
    name: 'Proyek IKN Nusantara - Core Area',
    code: 'IKN',
    location: 'Sepaku, Penajam Paser Utara, Kalimantan Timur',
    manager: 'Ir. Ahmad Fauzi',
    latitude: -0.9619,
    longitude: 116.7027,
  }
];

export const initialMaterialItems: MaterialItem[] = [
  {
    id: 'SP/MAT/0726/001',
    itemName: 'Semen Portland Composite (Tiga Roda)',
    quantity: 500,
    unit: 'Sak (50kg)',
    site: 'Proyek Sudirman Plaza',
    urgency: 'high',
    requestedBy: 'Andi Wijaya (Site Supervisor)',
    dateRequested: '2026-07-01',
    stage: 'completed',
    requestStatus: 'approved',
    approvedDate: '2026-07-02',
    purchase: {
      poNumber: 'PO-2026-0701',
      supplier: 'PT Surya Beton Abadi',
      unitPrice: 65000,
      totalPrice: 32500000,
      purchaseDate: '2026-07-03',
      status: 'ready_for_delivery',
    },
    delivery: {
      suratJalan: 'SJ-700912',
      driverName: 'Eko Prasetyo',
      driverPhone: '0812-3456-7890',
      vehiclePlate: 'B 9841 TQ',
      departureDate: '2026-07-05 08:00',
      eta: '2026-07-05 14:00',
      currentStatus: 'received',
      transitLogs: [
        { id: 't1', status: 'warehouse', timestamp: '2026-07-05 07:30', note: 'Material dimuat di Gudang Utama Jakarta' },
        { id: 't2', status: 'transit', timestamp: '2026-07-05 09:15', note: 'Truk keluar dari gerbang tol Semanggi' },
        { id: 't3', status: 'arrived', timestamp: '2026-07-05 13:40', note: 'Truk tiba di lokasi proyek, pembongkaran muatan' },
        { id: 't4', status: 'received', timestamp: '2026-07-05 14:15', note: 'Material diterima lengkap dan diverifikasi oleh Site Manager' }
      ],
      deliveredDate: '2026-07-05 14:15',
      receivedBy: 'Ir. Budi Santoso',
    }
  },
  {
    id: 'GM/MAT/0726/001',
    itemName: 'Besi Beton Ulir D16 (U-40) Krakatau Steel',
    quantity: 120,
    unit: 'Batang (12m)',
    site: 'Proyek Apartment Grand Merdeka',
    urgency: 'high',
    requestedBy: 'Rizky Pratama (Structure Engineer)',
    dateRequested: '2026-07-10',
    stage: 'delivery',
    requestStatus: 'approved',
    approvedDate: '2026-07-11',
    purchase: {
      poNumber: 'PO-2026-0715',
      supplier: 'PT Krakatau Baja Raya',
      unitPrice: 185000,
      totalPrice: 22200000,
      purchaseDate: '2026-07-12',
      status: 'ready_for_delivery',
    },
    delivery: {
      suratJalan: 'SJ-701205',
      driverName: 'Suryono',
      driverPhone: '0852-9876-5432',
      vehiclePlate: 'D 8831 UA',
      departureDate: '2026-07-15 13:00',
      eta: '2026-07-15 19:00',
      currentStatus: 'transit',
      transitLogs: [
        { id: 'tl1', status: 'warehouse', timestamp: '2026-07-15 11:30', note: 'Besi dimuat menggunakan derek di gudang pemasok' },
        { id: 'tl2', status: 'transit', timestamp: '2026-07-15 13:15', note: 'Truk berangkat menuju Bandung via Tol Purbaleunyi' },
        { id: 'tl3', status: 'transit', timestamp: '2026-07-15 16:45', note: 'Truk berada di Rest Area KM 97, kondisi aman' }
      ],
    }
  },
  {
    id: 'SP/MAT/0726/002',
    itemName: 'Beton Ready Mix K-350 (Slump 12)',
    quantity: 45,
    unit: 'm3 (Mubil Mixer)',
    site: 'Proyek Sudirman Plaza',
    urgency: 'high',
    requestedBy: 'Andi Wijaya (Site Supervisor)',
    dateRequested: '2026-07-14',
    stage: 'purchase',
    requestStatus: 'approved',
    approvedDate: '2026-07-14',
    purchase: {
      poNumber: 'PO-2026-0722',
      supplier: 'PT Pionirbeton Industri',
      unitPrice: 980000,
      totalPrice: 44100000,
      purchaseDate: '2026-07-15',
      status: 'processing',
    }
  },
  {
    id: 'GM/MAT/0726/002',
    itemName: 'Pasir Beton Extra Super (Cimalaka)',
    quantity: 8,
    unit: 'Truck Index 8',
    site: 'Proyek Apartment Grand Merdeka',
    urgency: 'medium',
    requestedBy: 'Siti Rahmawati (Site Manager)',
    dateRequested: '2026-07-12',
    stage: 'purchase',
    requestStatus: 'approved',
    approvedDate: '2026-07-13',
    purchase: {
      poNumber: 'PO-2026-0718',
      supplier: 'CV Pasir Berkah Bandung',
      unitPrice: 2100000,
      totalPrice: 16800000,
      purchaseDate: '2026-07-14',
      status: 'processing',
    }
  },
  {
    id: 'HM/MAT/0726/001',
    itemName: 'Kabel Listrik NYY 4x16 mm2 Supreme',
    quantity: 4,
    unit: 'Roll (50m)',
    site: 'Proyek Harbour View Mall',
    urgency: 'medium',
    requestedBy: 'Dedi Kusnadi (ME Supervisor)',
    dateRequested: '2026-07-15',
    stage: 'request',
    requestStatus: 'pending',
  },
  {
    id: 'HM/MAT/0726/002',
    itemName: 'Pipa PVC AW 4 inch Rucika',
    quantity: 150,
    unit: 'Batang (4m)',
    site: 'Proyek Harbour View Mall',
    urgency: 'medium',
    requestedBy: 'Dedi Kusnadi (ME Supervisor)',
    dateRequested: '2026-07-13',
    stage: 'delivery',
    requestStatus: 'approved',
    approvedDate: '2026-07-14',
    purchase: {
      poNumber: 'PO-2026-0720',
      supplier: 'Toko Bangunan Utama Jaya',
      unitPrice: 125000,
      totalPrice: 18750000,
      purchaseDate: '2026-07-14',
      status: 'ready_for_delivery',
    },
    delivery: {
      suratJalan: 'SJ-701311',
      driverName: 'Agus Salim',
      driverPhone: '0878-1234-5678',
      vehiclePlate: 'L 9283 AX',
      departureDate: '2026-07-15 15:30',
      eta: '2026-07-15 17:30',
      currentStatus: 'warehouse',
      transitLogs: [
        { id: 'tlp1', status: 'warehouse', timestamp: '2026-07-15 15:30', note: 'Material selesai dipacking dan dikelompokkan di dermaga pengiriman' }
      ]
    }
  },
  {
    id: 'IKN/MAT/0726/001',
    itemName: 'Baja WF 250 (Wide Flange) Gunung Garuda',
    quantity: 24,
    unit: 'Batang (12m)',
    site: 'Proyek IKN Nusantara - Core Area',
    urgency: 'high',
    requestedBy: 'Ir. Ahmad Fauzi (Project Manager)',
    dateRequested: '2026-07-05',
    stage: 'delivery',
    requestStatus: 'approved',
    approvedDate: '2026-07-06',
    purchase: {
      poNumber: 'PO-2026-0705',
      supplier: 'PT Gunung Garuda Steel',
      unitPrice: 4200000,
      totalPrice: 100800000,
      purchaseDate: '2026-07-08',
      status: 'ready_for_delivery',
    },
    delivery: {
      suratJalan: 'SJ-902340',
      driverName: 'Joko Susilo (Kargo Laut)',
      driverPhone: '0813-8888-9999',
      vehiclePlate: 'B 9204 WT (Container)',
      departureDate: '2026-07-10 09:00',
      eta: '2026-07-18 12:00',
      currentStatus: 'transit',
      transitLogs: [
        { id: 'ikn1', status: 'warehouse', timestamp: '2026-07-10 07:00', note: 'Baja WF dimuat ke container di Pelabuhan Tanjung Priok' },
        { id: 'ikn2', status: 'transit', timestamp: '2026-07-10 14:00', note: 'Kapal Cargo berangkat dari Jakarta menuju Pelabuhan Semayang Balikpapan' },
        { id: 'ikn3', status: 'transit', timestamp: '2026-07-14 10:00', note: 'Kapal kargo merapat di Pelabuhan Semayang, bersiap proses bongkar kontainer' }
      ]
    }
  },
  {
    id: 'SP/MAT/0726/003',
    itemName: 'Keramik Lantai 60x60 Granite (Indogress)',
    quantity: 300,
    unit: 'Dus',
    site: 'Proyek Sudirman Plaza',
    urgency: 'low',
    requestedBy: 'Ir. Budi Santoso (Project Manager)',
    dateRequested: '2026-07-14',
    stage: 'request',
    requestStatus: 'pending',
  }
];
